spring:
  application:
    name: warehouse
  datasource:
    url: jdbc:postgresql://localhost:5432/warehouse
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    sql:
      init:
        mode: always

