CREATE TABLE warehouse_users (
                                 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 name VARCHAR(255) NOT NULL,
                                 surname VARCHAR(255) NOT NULL,
                                 position VARCHAR(255) NOT NULL,
                                 email VARCHAR(255) UNIQUE NOT NULL,
                                 password VARCHAR(255) NOT NULL,
                                 role VARCHAR(255) NOT NULL
);
INSERT INTO warehouse_users (name, surname, position, email, password, role)
VALUES
    ('Алексей', 'Иванов', 'Кладовщик', 'alexey@warehouse.com', '$2a$10$PfxsQqIgVO83OA10cyoeN.TfROLKPkB5q5OnWQy6l8Kmo8Y4mfEoe', 'STOREKEEPER'),
    ('Марина', 'Петрова', 'Менеджер', 'marina@warehouse.com', '$2a$10$PfxsQqIgVO83OA10cyoeN.TfROLKPkB5q5OnWQy6l8Kmo8Y4mfEoe', 'MANAGER'),
    ('Дмитрий', 'Смирнов', 'Администратор', 'dmitry@warehouse.com', '$2a$10$PfxsQqIgVO83OA10cyoeN.TfROLKPkB5q5OnWQy6l8Kmo8Y4mfEoe', 'ADMIN');